### ISSUE TITLE
RSS订阅中，URL的域名有误

### ISSUE THREAD

**Issue by Gwyntoria** [mancuoj/weekly#1]
![image](https://github.com/user-attachments/assets/32bc88ec-290e-4e9c-8c99-533bf0c28ee1)

刚更新RSS订阅。虽然follow可以抓取全文，但还是习惯性地点击tittle去原网站阅读。此时发现原先带有weekly三级域名的链接无法被打开。

查看了订阅的xml和博客域名，发现xml中还保留了之前的域名。

**Comment by mancuoj** [comment]
感谢提醒，昨天改域名忘了改这部分了
